export const WorkoutActionTypes = {
    GET_WORKOUTS: 'GET_WORKOUTS',
    SET_WORKOUTS: 'SET_WORKOUTS',
    ADD_WORKOUTS: 'ADD_WORKOUTS',
    DELETE_WORKOUTS: 'DELETE_WORKOUTS',
    SELECT_WORKOUTS: 'SELECT_WORKOUTS',
    UPDATE_SELECTED_WORKOUTS: 'UPDATE_SELECTED_WORKOUTS',

    GET_WORKOUTS_START: 'GET_WORKOUTS_START',
    GET_WORKOUTS_SUCCESS: 'GET_WORKOUTS_SUCCESS',
    GET_WORKOUTS_FAILURE: 'GET_WORKOUTS_FAILURE',
}