export const ExerciseActionTypes = {
    GET_EXERCISES: 'GET_EXERCISES',
    SET_EXERCISES: 'SET_EXERCISES',
    ADD_EXERCISES: 'ADD_EXERCISES',
    DELETE_EXERCISES: 'DELETE_EXERCISES',
    SELECT_EXERCISES: 'SELECT_EXERCISES',
    UPDATE_SELECTED_EXERCISES: 'UPDATE_SELECTED_EXERCISES',

    GET_EXERCISES_START: 'GET_EXERCISES_START',
    GET_EXERCISES_SUCCESS: 'GET_EXERCISES_SUCCESS',
    GET_EXERCISES_FAILURE: 'GET_EXERCISES_FAILURE',
}